# Generated by Django 2.1 on 2018-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('greeting', models.CharField(default='', max_length=200)),
            ],
            options={
                'db_table': 'Birthday',
            },
        ),
    ]
